version: "2" 
services:
  billing:
    image: storjlabs/billing
    build:
      context: ../../
      dockerfile: ./dockerfiles/billing/billing-development.dockerfile
    volumes:
      - ../../billing:/billing
    environment:
      - STAGE=development
