version: "2"
services:
  billing:
    image: storjlabs/billing
    build:
      context: ../../
      dockerfile: ./dockerfiles/billing/billing-development.dockerfile
    volumes:
      - ../../billing/bin:/billing/bin
      - ../../billing/lib:/billing/lib
    environment:
      - STAGE=development
