version: 2
services:
  base-service:
    image: storjlabs/storjmodules
    build:
      context: ../../
      dockerfile: ./dockerfiles/storjmodules/storjmodules-development.dockerfile
    volumes:
      - ../..:/storj-base
    environment:
      - STAGE=development
